// Auto-generated by scripts/ipc-codegen/extract.mjs
// Source: .tmp/official-app/.vite/build/index.js
// DO NOT EDIT — re-run the script to refresh.

// ----- claude.buddy::Buddy -----
export interface BuddyArgs {
  setName: undefined;
  pickDevice: undefined;
  submitPin: undefined;
  preview: undefined;
  install: undefined;
}
export interface BuddyReturn {
  setName: void;
  pickDevice: void;
  submitPin: void;
  preview: void;
  install: void;
}

// ----- claude.buddy::BuddyBleTransport -----
export interface BuddyBleTransportArgs {
  rx: undefined;
  reportState: {
  // unparsed: <no body>
};
  log: undefined;
}
export interface BuddyBleTransportReturn {
  rx: void;
  reportState: void;
  log: void;
}

// ----- claude.coworkArtifact::CoworkArtifactBridge -----
export interface CoworkArtifactBridgeArgs {
  callMcpTool: undefined;
  askClaude: {
  // unparsed: typeof e!="string"
  // unparsed: !(e.length<=32e3)
};
  runScheduledTask: undefined;
  navigateHost: {
  // unparsed: <no body>
};
  openExternalUrl: undefined;
}
export interface CoworkArtifactBridgeReturn {
  callMcpTool: {
  // unparsed: !(Array.isArray(e.content)&&e.content.every(A=>_2i(A)))
  // unparsed: (typeof e.structuredContent<"u",typeof e.isError<"u"&&typeof e.isError!="boolean")
};
  askClaude: {
  text: string;
  isError?: boolean;
};
  runScheduledTask: {
  sessionId?: string;
  isError?: boolean;
  error?: string;
};
  navigateHost: void;
  openExternalUrl: void;
}

// ----- claude.hybrid::DesktopIntl -----
export interface DesktopIntlArgs {
  requestLocaleChange: undefined;
}
export interface DesktopIntlReturn {
  requestLocaleChange: void;
}

// ----- claude.internal.findInPage::FindInPage -----
export interface FindInPageArgs {
  findInPage: undefined;
}
export interface FindInPageReturn {
  findInPage: void;
}

// ----- claude.internal.ui::QuickWindow -----
export interface QuickWindowArgs {
  requestDismiss: undefined;
  requestDismissWithPayload: {
  // unparsed: <no body>
};
  requestSkooch: undefined;
}
export interface QuickWindowReturn {
  requestDismiss: void;
  requestDismissWithPayload: void;
  requestSkooch: void;
}

// ----- claude.officeAddin::OfficeAddinFiles -----
export interface OfficeAddinFilesArgs {
  getConnectedFiles: undefined;
  focusFile: undefined;
  selectFile: undefined;
  updateActiveConversationSummary: undefined;
}
export interface OfficeAddinFilesReturn {
  getConnectedFiles: void;
  focusFile: void;
  selectFile: void;
  updateActiveConversationSummary: void;
}

// ----- claude.settings::AppConfig -----
export interface AppConfigArgs {
  setAppFeature: undefined;
  setIsUsingBuiltInNodeForMcp: undefined;
  setIsDxtAutoUpdatesEnabled: undefined;
}
export interface AppConfigReturn {
  setAppFeature: void;
  setIsUsingBuiltInNodeForMcp: void;
  setIsDxtAutoUpdatesEnabled: void;
}

// ----- claude.settings::AppPreferences -----
export interface AppPreferencesArgs {
  setPreference: undefined;
}
export interface AppPreferencesReturn {
  setPreference: void;
}

// ----- claude.settings::Extensions -----
export interface ExtensionsArgs {
  getIsUpdateAvailable: undefined;
  getManifestCompatibilityResult: {
  // unparsed: <no body>
};
  getExtensionSettings: undefined;
  setExtensionSettings: undefined;
  installDxt: undefined;
  installDxtUnpacked: undefined;
  installDxtFromDirectory: undefined;
  handleDxtFile: undefined;
  deleteExtension: undefined;
  showExtensionInFolder: undefined;
  getExtension: {
  // unparsed: <no body>
};
  getExtensions: undefined;
  getExtensionVersion: undefined;
  getExtensionVersions: undefined;
  installExtensionFromPreview: undefined;
}
export interface ExtensionsReturn {
  getIsUpdateAvailable: void;
  getManifestCompatibilityResult: {
  // unparsed: <no body>
};
  getExtensionSettings: {
  // unparsed: <no body>
};
  setExtensionSettings: void;
  installDxt: void;
  installDxtUnpacked: void;
  installDxtFromDirectory: void;
  handleDxtFile: void;
  deleteExtension: void;
  showExtensionInFolder: void;
  getExtension: {
  data: /* njt */ unknown;
  url: string;
};
  getExtensions: {
  data: /* ajt */ unknown;
  url: string;
};
  getExtensionVersion: void;
  getExtensionVersions: void;
  installExtensionFromPreview: void;
}

// ----- claude.settings::FilePickers -----
export interface FilePickersArgs {
  getDirectoryPath: undefined;
  getFilePath: undefined;
}
export interface FilePickersReturn {
  getDirectoryPath: void;
  getFilePath: void;
}

// ----- claude.settings::GlobalShortcut -----
export interface GlobalShortcutArgs {
  setGlobalShortcut: undefined;
}
export interface GlobalShortcutReturn {
  setGlobalShortcut: void;
}

// ----- claude.settings::MCP -----
export interface MCPArgs {
  setMcpServerConfigs: {
  // unparsed: <no body>
};
  getMcpServersConfig: undefined;
  revealServerLog: undefined;
}
export interface MCPReturn {
  setMcpServerConfigs: void;
  getMcpServersConfig: {
  // unparsed: <no body>
};
  revealServerLog: void;
}

// ----- claude.settings::Startup -----
export interface StartupArgs {
  setStartupOnLoginEnabled: undefined;
  setMenuBarEnabled: undefined;
}
export interface StartupReturn {
  setStartupOnLoginEnabled: void;
  setMenuBarEnabled: void;
}

// ----- claude.settings::SupportBundle -----
export interface SupportBundleArgs {
  submitAction: {
  // unparsed: <no body>
};
}
export interface SupportBundleReturn {
  submitAction: void;
}

// ----- claude.simulator::Simulator -----
export interface SimulatorArgs {
  attach: undefined;
  detach: undefined;
  installAndLaunch: {
  udid: string;
  appPath: string;
  bundleId?: string;
  kind?: string;
};
  gesture: undefined;
}
export interface SimulatorReturn {
  attach: void;
  detach: void;
  installAndLaunch: void;
  gesture: void;
}

// ----- claude.web::Account -----
export interface AccountArgs {
  setAccountDetails: {
  // unparsed: <no body>
};
}
export interface AccountReturn {
  setAccountDetails: void;
}

// ----- claude.web::AgentModeFeedback -----
export interface AgentModeFeedbackArgs {
  openFeedbackWindow: {
  // unparsed: <no body>
};
  openFeedbackAndConfirmReinstall: {
  // unparsed: <no body>
};
  reportErrorToSlack: undefined;
}
export interface AgentModeFeedbackReturn {
  openFeedbackWindow: {
  // unparsed: <no body>
};
  openFeedbackAndConfirmReinstall: {
  // unparsed: <no body>
};
  reportErrorToSlack: void;
}

// ----- claude.web::Auth -----
export interface AuthArgs {
  doAuthInBrowser: undefined;
}
export interface AuthReturn {
  doAuthInBrowser: void;
}

// ----- claude.web::BrowserNavigation -----
export interface BrowserNavigationArgs {
  reportNavigationState: {
  canGoBack: boolean;
  canGoForward: boolean;
};
}
export interface BrowserNavigationReturn {
  reportNavigationState: void;
}

// ----- claude.web::BuddyRemoteFeed -----
export interface BuddyRemoteFeedArgs {
  sync: undefined;
}
export interface BuddyRemoteFeedReturn {
  sync: void;
}

// ----- claude.web::CCDScheduledTasks -----
export interface CCDScheduledTasksArgs {
  getScheduledTaskFileContent: undefined;
  updateScheduledTaskFileContent: undefined;
  updateScheduledTaskStatus: undefined;
  createScheduledTask: {
  name: string;
  prompt: string;
  description: string;
  cronExpression?: string;
  fireAt?: number;
  model?: string;
  spaceId?: string;
  cwd?: string;
  useWorktree?: boolean;
  sourceBranch?: string;
  permissionMode?: /* rB */ unknown;
  chromePermissionMode?: /* QV */ unknown;
  disableJitter?: boolean;
  // unparsed: typeof e.userSelectedFolders<"u"&&!(Array.isArray(e.userSelectedFolders)&&e.userSelectedFolders.every(A=>typeof A=="string"))
};
  updateScheduledTask: {
  scheduledTaskId: string;
  prompt?: string;
  description?: string;
  cronExpression?: string;
  fireAt?: number;
  model?: string;
  spaceId?: string;
  cwd?: string;
  useWorktree?: boolean;
  sourceBranch?: string;
  permissionMode?: /* rB */ unknown;
  chromePermissionMode?: /* QV */ unknown;
  disableJitter?: boolean;
  // unparsed: typeof e.userSelectedFolders<"u"&&!(Array.isArray(e.userSelectedFolders)&&e.userSelectedFolders.every(A=>typeof A=="string"))
};
  removeApprovedPermission: undefined;
}
export interface CCDScheduledTasksReturn {
  getScheduledTaskFileContent: void;
  updateScheduledTaskFileContent: void;
  updateScheduledTaskStatus: void;
  createScheduledTask: void;
  updateScheduledTask: void;
  removeApprovedPermission: void;
}

// ----- claude.web::ClaudeCode -----
export interface ClaudeCodeArgs {
  resolveLocalSettings: undefined;
}
export interface ClaudeCodeReturn {
  resolveLocalSettings: {
  model?: /* T$A */ unknown;
  fastMode?: /* v$A */ unknown;
  fastModePerSessionOptIn?: /* v$A */ unknown;
  defaultPermissionMode?: /* T$A */ unknown;
  sshHostAllowlist?: /* _Ut */ unknown;
};
}

// ----- claude.web::ClaudeVM -----
export interface ClaudeVMArgs {
  startVM: undefined;
  setForceDisableHostLoop: undefined;
  setYukonSilverConfig: {
  autoDownloadInBackground: boolean;
  autoStartOnUserIntent: boolean;
  memoryGB: number;
  mcpToolTimeoutMs?: number;
  mcpToolTimeoutOverridesMs?: /* qYt */ unknown;
  defaultSubagentModel?: string;
  effort?: string;
  effortByModel?: /* VYt */ unknown;
  autoCompactWindow?: number;
  // unparsed: (typeof e.maxThinkingTokens<"u",typeof e.useCoworkOauth<"u"&&typeof e.useCoworkOauth!="boolean")
  // unparsed: typeof e.supports1mContext<"u"&&!(Array.isArray(e.supports1mContext)&&e.supports1mContext.every(A=>typeof A=="string"))
  // unparsed: typeof e.allowedModels<"u"&&!(Array.isArray(e.allowedModels)&&e.allowedModels.every(A=>typeof A=="string"))
};
}
export interface ClaudeVMReturn {
  startVM: {
  success: boolean;
  error?: string;
};
  setForceDisableHostLoop: void;
  setYukonSilverConfig: void;
}

// ----- claude.web::ComputerUseTcc -----
export interface ComputerUseTccArgs {
  openSystemSettings: undefined;
  getCurrentSessionGrants: undefined;
  revokeGrant: undefined;
}
export interface ComputerUseTccReturn {
  openSystemSettings: void;
  getCurrentSessionGrants: void;
  revokeGrant: void;
}

// ----- claude.web::CoworkArtifacts -----
export interface CoworkArtifactsArgs {
  getArtifactMetadata: undefined;
  getArtifactThumbnail: undefined;
  deleteArtifact: undefined;
  getArtifactIndexHtmlPath: undefined;
  showArtifact: undefined;
  parkAndCaptureArtifact: {
  x: number;
  y: number;
  width: number;
  height: number;
};
  restoreArtifactVersion: undefined;
  setArtifactStarred: undefined;
  setArtifactMcpTools: undefined;
  shareArtifact: undefined;
  unshareArtifact: undefined;
  refreshImportedArtifact: undefined;
  importArtifact: undefined;
}
export interface CoworkArtifactsReturn {
  getArtifactMetadata: void;
  getArtifactThumbnail: void;
  deleteArtifact: void;
  getArtifactIndexHtmlPath: void;
  showArtifact: void;
  parkAndCaptureArtifact: void;
  restoreArtifactVersion: void;
  setArtifactStarred: void;
  setArtifactMcpTools: void;
  shareArtifact: {
  ok: boolean;
  url?: string;
  error?: string;
};
  unshareArtifact: void;
  refreshImportedArtifact: {
  // unparsed: <no body>
};
  importArtifact: {
  // unparsed: <no body>
};
}

// ----- claude.web::CoworkFilePreview -----
export interface CoworkFilePreviewArgs {
  show: undefined;
  parkAndCapture: {
  x: number;
  y: number;
  width: number;
  height: number;
};
}
export interface CoworkFilePreviewReturn {
  show: {
  ok: boolean;
  declineReason?: string;
};
  parkAndCapture: void;
}

// ----- claude.web::CoworkMemory -----
export interface CoworkMemoryArgs {
  writeGlobalMemory: undefined;
  listAccountMemories: undefined;
  readAccountMemory: undefined;
  writeAccountMemory: undefined;
  deleteAccountMemory: undefined;
}
export interface CoworkMemoryReturn {
  writeGlobalMemory: void;
  listAccountMemories: void;
  readAccountMemory: void;
  writeAccountMemory: void;
  deleteAccountMemory: void;
}

// ----- claude.web::CoworkRadar -----
export interface CoworkRadarArgs {
  dismissCard: undefined;
  setCardStatus: undefined;
  recordCardEngagement: undefined;
  adoptSession: undefined;
}
export interface CoworkRadarReturn {
  dismissCard: void;
  setCardStatus: void;
  recordCardEngagement: void;
  adoptSession: void;
}

// ----- claude.web::CoworkScheduledTasks -----
export interface CoworkScheduledTasksArgs {
  getScheduledTaskFileContent: undefined;
  updateScheduledTaskFileContent: undefined;
  updateScheduledTaskStatus: undefined;
  createScheduledTask: {
  name: string;
  prompt: string;
  description: string;
  cronExpression?: string;
  fireAt?: number;
  model?: string;
  spaceId?: string;
  cwd?: string;
  useWorktree?: boolean;
  sourceBranch?: string;
  permissionMode?: /* rB */ unknown;
  chromePermissionMode?: /* QV */ unknown;
  disableJitter?: boolean;
  // unparsed: typeof e.userSelectedFolders<"u"&&!(Array.isArray(e.userSelectedFolders)&&e.userSelectedFolders.every(A=>typeof A=="string"))
};
  updateScheduledTask: {
  scheduledTaskId: string;
  prompt?: string;
  description?: string;
  cronExpression?: string;
  fireAt?: number;
  model?: string;
  spaceId?: string;
  cwd?: string;
  useWorktree?: boolean;
  sourceBranch?: string;
  permissionMode?: /* rB */ unknown;
  chromePermissionMode?: /* QV */ unknown;
  disableJitter?: boolean;
  // unparsed: typeof e.userSelectedFolders<"u"&&!(Array.isArray(e.userSelectedFolders)&&e.userSelectedFolders.every(A=>typeof A=="string"))
};
  removeApprovedPermission: undefined;
  clearChromePermissions: undefined;
}
export interface CoworkScheduledTasksReturn {
  getScheduledTaskFileContent: void;
  updateScheduledTaskFileContent: void;
  updateScheduledTaskStatus: void;
  createScheduledTask: void;
  updateScheduledTask: void;
  removeApprovedPermission: void;
  clearChromePermissions: void;
}

// ----- claude.web::CoworkSpaces -----
export interface CoworkSpacesArgs {
  getSpace: undefined;
  createSpace: {
  name: string;
  description?: string;
  instructions?: string;
  origin?: string;
};
  updateSpace: undefined;
  deleteSpace: undefined;
  addFolderToSpace: undefined;
  removeFolderFromSpace: undefined;
  addProjectToSpace: undefined;
  removeProjectFromSpace: undefined;
  addLinkToSpace: undefined;
  removeLinkFromSpace: undefined;
  getAutoMemoryDir: undefined;
  listFolderContents: undefined;
  readFileContents: undefined;
  openFile: undefined;
  createSpaceFolder: undefined;
  copyFilesToSpaceFolder: undefined;
  classifySessions: undefined;
  summarizeSpace: undefined;
  setAutoDescription: undefined;
}
export interface CoworkSpacesReturn {
  getSpace: void;
  createSpace: void;
  updateSpace: void;
  deleteSpace: void;
  addFolderToSpace: void;
  removeFolderFromSpace: void;
  addProjectToSpace: void;
  removeProjectFromSpace: void;
  addLinkToSpace: void;
  removeLinkFromSpace: void;
  getAutoMemoryDir: void;
  listFolderContents: void;
  readFileContents: void;
  openFile: void;
  createSpaceFolder: void;
  copyFilesToSpaceFolder: void;
  classifySessions: void;
  summarizeSpace: void;
  setAutoDescription: void;
}

// ----- claude.web::CustomPlugins -----
export interface CustomPluginsArgs {
  addMarketplace: undefined;
  removeMarketplace: undefined;
  refreshMarketplace: undefined;
  listMarketplaces: undefined;
  installPlugin: undefined;
  updatePlugin: undefined;
  uninstallPlugin: undefined;
  listInstalledPlugins: undefined;
  listAvailablePlugins: undefined;
  listRemotePluginsPage: undefined;
  checkPluginHasLocalChanges: undefined;
  installLocalOrgPlugin: undefined;
}
export interface CustomPluginsReturn {
  addMarketplace: void;
  removeMarketplace: void;
  refreshMarketplace: {
  // unparsed: <no body>
};
  listMarketplaces: void;
  installPlugin: {
  // unparsed: <no body>
};
  updatePlugin: {
  // unparsed: <no body>
};
  uninstallPlugin: void;
  listInstalledPlugins: void;
  listAvailablePlugins: void;
  listRemotePluginsPage: {
  // unparsed: <no body>
};
  checkPluginHasLocalChanges: {
  // unparsed: <no body>
};
  installLocalOrgPlugin: {
  // unparsed: <no body>
};
}

// ----- claude.web::DesktopNotifications -----
export interface DesktopNotificationsArgs {
  showNotification: undefined;
}
export interface DesktopNotificationsReturn {
  showNotification: void;
}

// ----- claude.web::FileSystem -----
export interface FileSystemArgs {
  writeFileDownloadAndOpen: undefined;
  writeFileDownload: undefined;
  whichApplication: undefined;
  browseFolder: undefined;
  browseFolders: undefined;
  listDirectory: undefined;
  getSystemPath: {
  // unparsed: <no body>
};
  openLocalFile: undefined;
  listFilesInFolder: undefined;
  readLocalFile: undefined;
  getLocalFileThumbnail: undefined;
  writeLocalFile: undefined;
  showInFolder: undefined;
  savePastedFile: undefined;
  browseFiles: undefined;
  exportLocalFileToGoogleDrive: undefined;
  promoteScratchpadFile: undefined;
}
export interface FileSystemReturn {
  writeFileDownloadAndOpen: void;
  writeFileDownload: void;
  whichApplication: void;
  browseFolder: void;
  browseFolders: void;
  listDirectory: {
  error?: string;
  // unparsed: !(Array.isArray(e.directories)&&e.directories.every(A=>typeof A=="string"))
};
  getSystemPath: void;
  openLocalFile: void;
  listFilesInFolder: void;
  readLocalFile: void;
  getLocalFileThumbnail: void;
  writeLocalFile: void;
  showInFolder: void;
  savePastedFile: {
  path?: string;
  error?: string;
};
  browseFiles: void;
  exportLocalFileToGoogleDrive: {
  driveUrl?: string;
  driveFileId?: string;
  errorCode?: string;
  mcpServerId?: string;
  mcpServerUrl?: string;
};
  promoteScratchpadFile: {
  hostPath: string;
  vmOutputsPath: string;
};
}

// ----- claude.web::FindInPageProvider -----
export interface FindInPageProviderArgs {
  setProviderActive: undefined;
  reportFindResult: undefined;
}
export interface FindInPageProviderReturn {
  setProviderActive: void;
  reportFindResult: void;
}

// ----- claude.web::FramebufferPreview -----
export interface FramebufferPreviewArgs {
  listSources: undefined;
  attach: undefined;
  detach: undefined;
  setStreamHints: undefined;
  sendPointer: undefined;
  sendKey: undefined;
  sendScroll: undefined;
}
export interface FramebufferPreviewReturn {
  listSources: void;
  attach: {
  sessionId: string;
  name: string;
  origin: string;
  width: number;
  height: number;
};
  detach: void;
  setStreamHints: void;
  sendPointer: void;
  sendKey: void;
  sendScroll: void;
}

// ----- claude.web::GrandPrix -----
export interface GrandPrixArgs {
  pair: undefined;
  disconnect: undefined;
}
export interface GrandPrixReturn {
  pair: {
  paired: boolean;
  error?: string;
};
  disconnect: void;
}

// ----- claude.web::Launch -----
export interface LaunchArgs {
  getLogs: undefined;
  stopServer: undefined;
  showPreview: undefined;
  hidePreview: undefined;
  destroyPreview: undefined;
  refreshPreview: undefined;
  setPreviewViewport: undefined;
  clearPreviewViewport: undefined;
  setPreviewColorScheme: undefined;
  toggleSelectionMode: undefined;
  startFromConfig: undefined;
  getConfiguredServices: undefined;
  getAutoVerify: undefined;
  setAutoVerify: undefined;
  getPreviewUrl: undefined;
  navigatePreview: undefined;
  goBack: undefined;
  goForward: undefined;
  capturePreviewScreenshot: undefined;
  loadHtmlPreview: undefined;
  pickHtmlFile: undefined;
  deployPreview: undefined;
  suggestDeployName: undefined;
  unpublishDeploy: undefined;
}
export interface LaunchReturn {
  getLogs: void;
  stopServer: void;
  showPreview: void;
  hidePreview: void;
  destroyPreview: void;
  refreshPreview: void;
  setPreviewViewport: void;
  clearPreviewViewport: void;
  setPreviewColorScheme: void;
  toggleSelectionMode: void;
  startFromConfig: {
  serverId?: string;
  error?: string;
};
  getConfiguredServices: void;
  getAutoVerify: void;
  setAutoVerify: void;
  getPreviewUrl: void;
  navigatePreview: void;
  goBack: void;
  goForward: void;
  capturePreviewScreenshot: void;
  loadHtmlPreview: void;
  pickHtmlFile: void;
  deployPreview: void;
  suggestDeployName: void;
  unpublishDeploy: void;
}

// ----- claude.web::LocalAgentModeSessions -----
export interface LocalAgentModeSessionsArgs {
  start: {
  message: string;
  sessionId?: string;
  model?: string;
  permissionMode?: /* rB */ unknown;
  title?: string;
  systemPrompt?: string;
  mcpServers?: /* mUe */ unknown;
  orgCliExecPolicies?: /* CUe */ unknown;
  enabledCliOps?: /* dFt */ unknown;
  messageUuid?: string;
  emailAddress?: string;
  scheduledTaskId?: string;
  spaceId?: string;
  otelConfig?: /* EUe */ unknown;
  channel?: string;
  sessionType?: string;
  parentSessionId?: string;
  memoryEnabled?: boolean;
  skillsEnabled?: boolean;
  pluginsEnabled?: boolean;
  imagineSystemPrompt?: string;
  chromeSkipAllPermissionChecks?: boolean;
  // unparsed: typeof e.remoteMcpServers<"u"&&!(Array.isArray(e.remoteMcpServers)&&e.remoteMcpServers.every(A=>DUe(A)))
  // unparsed: typeof e.images<"u"&&!(Array.isArray(e.images)&&e.images.every(A=>OiA(A)))
  // unparsed: typeof e.userSelectedFolders<"u"&&!(Array.isArray(e.userSelectedFolders)&&e.userSelectedFolders.every(A=>typeof A=="string"))
  // unparsed: typeof e.userSelectedFiles<"u"&&!(Array.isArray(e.userSelectedFiles)&&e.userSelectedFiles.every(A=>typeof A=="string"))
  // unparsed: typeof e.egressAllowedDomains<"u"&&!(Array.isArray(e.egressAllowedDomains)&&e.egressAllowedDomains.every(A=>typeof A=="string"))
  // unparsed: (typeof e.enabledMcpTools<"u",typeof e.accountName<"u"&&typeof e.accountName!="string")
  // unparsed: typeof e.userSelectedProjectUuids<"u"&&!(Array.isArray(e.userSelectedProjectUuids)&&e.userSelectedProjectUuids.every(A=>typeof A=="string"))
  // unparsed: typeof e.chromeAllowedDomains<"u"&&!(Array.isArray(e.chromeAllowedDomains)&&e.chromeAllowedDomains.every(A=>typeof A=="string"))
  // unparsed: typeof e.cuAppHints<"u"&&!(Array.isArray(e.cuAppHints)&&e.cuAppHints.every(A=>mGA(A)))
};
  sendMessage: undefined;
  setModel: undefined;
  setPermissionMode: undefined;
  setChromePermissionMode: undefined;
  noteCuWindowMentions: undefined;
  stop: undefined;
  rewind: undefined;
  archive: undefined;
  delete: undefined;
  updateSession: undefined;
  getSession: undefined;
  getTranscript: undefined;
  searchSessions: undefined;
  respondToToolPermission: undefined;
  openOutputsDir: undefined;
  shareSession: undefined;
  submitTranscriptFeedback: undefined;
  getTranscriptFeedback: undefined;
  setDraftSessionFolders: undefined;
  getSupportedCommands: undefined;
  addTrustedFolder: undefined;
  removeTrustedFolder: undefined;
  isFolderTrusted: undefined;
  addFolderToSession: undefined;
  setMcpServers: undefined;
  replaceRemoteMcpServers: undefined;
  replaceEnabledMcpTools: undefined;
  setFocusedSession: undefined;
  getLocalSkillFiles: undefined;
  saveLocalSkill: undefined;
  setLocalSkillEnabled: undefined;
  deleteLocalSkill: undefined;
  revealLocalSkill: undefined;
  respondDirectoryServers: undefined;
  respondPluginSearch: undefined;
  respondSlashMenuSkills: undefined;
  mcpCallTool: undefined;
  mcpReadResource: undefined;
  mcpListResources: undefined;
  getSessionsForScheduledTask: undefined;
  abandonBridgeEnvironment: undefined;
  setSessionsBridgeEnabled: undefined;
  respondBridgePermissionPreflight: undefined;
  authorizeDirectMcpServer: undefined;
  disconnectDirectMcpServer: undefined;
}
export interface LocalAgentModeSessionsReturn {
  start: {
  sessionId: string;
};
  sendMessage: void;
  setModel: void;
  setPermissionMode: void;
  setChromePermissionMode: void;
  noteCuWindowMentions: void;
  stop: void;
  rewind: void;
  archive: void;
  delete: void;
  updateSession: void;
  getSession: void;
  getTranscript: void;
  searchSessions: void;
  respondToToolPermission: void;
  openOutputsDir: void;
  shareSession: {
  success: boolean;
  filePath?: string;
  error?: string;
};
  submitTranscriptFeedback: void;
  getTranscriptFeedback: void;
  setDraftSessionFolders: void;
  getSupportedCommands: void;
  addTrustedFolder: void;
  removeTrustedFolder: void;
  isFolderTrusted: void;
  addFolderToSession: {
  ok: boolean;
  folderPath?: string;
  error?: string;
};
  setMcpServers: {
  enabledMcpTools: /* jOt */ unknown;
};
  replaceRemoteMcpServers: {
  enabledMcpTools: /* jOt */ unknown;
};
  replaceEnabledMcpTools: {
  enabledMcpTools: /* jOt */ unknown;
};
  setFocusedSession: void;
  getLocalSkillFiles: void;
  saveLocalSkill: {
  ok: boolean;
  error?: string;
};
  setLocalSkillEnabled: {
  ok: boolean;
  error?: string;
};
  deleteLocalSkill: {
  ok: boolean;
  error?: string;
};
  revealLocalSkill: void;
  respondDirectoryServers: void;
  respondPluginSearch: void;
  respondSlashMenuSkills: void;
  mcpCallTool: {
  // unparsed: <no body>
};
  mcpReadResource: {
  // unparsed: !(Array.isArray(e.contents)&&e.contents.every(A=>!0))
};
  mcpListResources: void;
  getSessionsForScheduledTask: void;
  abandonBridgeEnvironment: void;
  setSessionsBridgeEnabled: void;
  respondBridgePermissionPreflight: void;
  authorizeDirectMcpServer: {
  ok: boolean;
  error?: string;
  cancelled?: boolean;
  // unparsed: typeof e.tools<"u"&&!(Array.isArray(e.tools)&&e.tools.every(A=>Sb(A)))
};
  disconnectDirectMcpServer: void;
}

// ----- claude.web::LocalPlugins -----
export interface LocalPluginsArgs {
  getPlugins: undefined;
  getDownloadedRemotePlugins: undefined;
  syncRemotePlugins: undefined;
  listSkillFiles: undefined;
  uploadPlugin: undefined;
  deletePlugin: undefined;
  setPluginEnabled: undefined;
  getPluginOAuthStatus: undefined;
  startPluginOAuthFlow: undefined;
  revokePluginOAuth: undefined;
  getPluginCliStatus: undefined;
  setPluginEnvVars: undefined;
  setPluginOAuthClient: undefined;
  getPluginShimOps: undefined;
  setPluginShimPermission: undefined;
}
export interface LocalPluginsReturn {
  getPlugins: void;
  getDownloadedRemotePlugins: void;
  syncRemotePlugins: {
  // unparsed: !(Array.isArray(e.newlyInstalled)&&e.newlyInstalled.every(A=>IYt(A)))
};
  listSkillFiles: {
  success: boolean;
  error?: string;
  // unparsed: typeof e.files<"u"&&!(Array.isArray(e.files)&&e.files.every(A=>rYt(A)))
};
  uploadPlugin: {
  success: boolean;
  filePath?: string;
  pluginId?: string;
  error?: string;
  isUserFacingError?: boolean;
  isNew?: boolean;
  errorCode?: /* sYt */ unknown;
};
  deletePlugin: {
  success: boolean;
  error?: string;
};
  setPluginEnabled: {
  success: boolean;
  error?: string;
  enabled?: boolean;
};
  getPluginOAuthStatus: {
  // unparsed: <no body>
};
  startPluginOAuthFlow: {
  success: boolean;
  error?: string;
};
  revokePluginOAuth: void;
  getPluginCliStatus: {
  // unparsed: <no body>
};
  setPluginEnvVars: {
  // unparsed: <no body>
};
  setPluginOAuthClient: {
  // unparsed: <no body>
};
  getPluginShimOps: void;
  setPluginShimPermission: void;
}

// ----- claude.web::LocalSessionEnvironment -----
export interface LocalSessionEnvironmentArgs {
  save: {
  // unparsed: <no body>
};
}
export interface LocalSessionEnvironmentReturn {
  save: {
  success: boolean;
};
}

// ----- claude.web::LocalSessions -----
export interface LocalSessionsArgs {
  shareSession: undefined;
  start: {
  cwd: string;
  message: string;
  sessionId?: string;
  model?: string;
  useWorktree?: boolean;
  sourceBranch?: string;
  title?: string;
  systemPrompt?: string;
  mcpServers?: /* mUe */ unknown;
  permissionMode?: /* rB */ unknown;
  scheduledTaskId?: string;
  emailAddress?: string;
  spaceId?: string;
  systemPromptAppend?: string;
  messageUuid?: string;
  agent?: string;
  effort?: string;
  fastMode?: boolean;
  rendererSurface?: string;
  classifierSummaryEnabled?: boolean;
  // unparsed: typeof e.remoteMcpServers<"u"&&!(Array.isArray(e.remoteMcpServers)&&e.remoteMcpServers.every(A=>DUe(A)))
  // unparsed: typeof e.images<"u"&&!(Array.isArray(e.images)&&e.images.every(A=>OiA(A)))
  // unparsed: (typeof e.enabledMcpTools<"u",typeof e.sshConfig<"u"&&!Hd(e.sshConfig))
  // unparsed: typeof e.additionalDirectories<"u"&&!(Array.isArray(e.additionalDirectories)&&e.additionalDirectories.every(A=>typeof A=="string"))
};
  forkSession: undefined;
  sendMessage: undefined;
  setModel: undefined;
  setEffort: undefined;
  getEffort: undefined;
  setFastMode: undefined;
  getContextUsage: undefined;
  startSideChat: undefined;
  sendSideChatMessage: undefined;
  stopSideChat: undefined;
  summarizeSession: undefined;
  summarizeTranscript: undefined;
  stopSessionSummary: undefined;
  stop: undefined;
  interrupt: undefined;
  stopTask: undefined;
  cancelQueuedMessage: undefined;
  logCliEvent: undefined;
  clearSession: undefined;
  rewind: undefined;
  getUncommittedChanges: undefined;
  archive: undefined;
  unarchive: undefined;
  delete: undefined;
  updateSession: undefined;
  getSession: undefined;
  getSessionsForScheduledTask: undefined;
  getGitInfo: undefined;
  getLocalBranches: undefined;
  getGitDiff: undefined;
  getGitDiffStats: undefined;
  getDiffFileContent: undefined;
  getGitCommits: undefined;
  getCommitDiff: undefined;
  getTranscript: undefined;
  searchSessions: undefined;
  openInVSCode: undefined;
  getInstalledEditors: undefined;
  openInEditor: undefined;
  pickSessionFile: undefined;
  pickFileAtCwd: undefined;
  readFileAtCwd: undefined;
  readSessionFile: undefined;
  listSessionDirectory: undefined;
  readSessionImageAsDataUrl: undefined;
  writeSessionFile: undefined;
  startPty: undefined;
  stopPty: undefined;
  resizePty: undefined;
  writePty: undefined;
  startShellPty: undefined;
  stopShellPty: undefined;
  resizeShellPty: undefined;
  writeShellPty: undefined;
  getShellPtyBuffer: undefined;
  runBashCommand: undefined;
  respondToToolPermission: undefined;
  checkTrust: undefined;
  saveTrust: undefined;
  setPermissionMode: undefined;
  getPermissionMode: undefined;
  launchUltrareview: undefined;
  submitFeedback: undefined;
  addDirectories: undefined;
  getDefaultPermissionMode: undefined;
  getSupportedCommands: undefined;
  getAgents: undefined;
  createAgent: {
  name: string;
  description: string;
  systemPrompt: string;
  scope: string;
  cwd?: string;
};
  getPlanForSession: undefined;
  setMcpServers: undefined;
  replaceRemoteMcpServers: undefined;
  replaceEnabledMcpTools: undefined;
  setFocusedSession: undefined;
  setAvailableCodeModels: undefined;
  testSSHConnection: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  validateSSHPath: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  listSSHDirectory: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  getSSHGitInfo: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  getSSHSupportedCommands: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  checkRemoteTrust: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  resolveSSHSettings: {
  sshHost: string;
  sshPort?: number;
  sshIdentityFile?: string;
  remoteCwd?: string;
};
  ensureSSHConnected: undefined;
  setSSHConfigs: undefined;
  setTrustedSSHHosts: undefined;
  importCliSession: undefined;
  setVisibility: undefined;
  checkGhAvailable: undefined;
  listGhIssues: undefined;
  getGhIssue: undefined;
  isWorkingTreeDirty: undefined;
  getWorkingTreeStatus: undefined;
  commitAllChanges: undefined;
  stashWorkingTree: undefined;
  commitWipForBranchSwitch: undefined;
  discardWorkingTree: undefined;
  generateLocalPrContent: undefined;
  reviewDiff: undefined;
  ensureBranchPushed: undefined;
  createLocalPr: {
  cwd: string;
  title: string;
  body?: string;
  baseBranch?: string;
  draft?: boolean;
  sessionId?: string;
};
  getPrChecks: undefined;
  getPrStateForBranch: undefined;
  getPrDetails: undefined;
  getPrReviewComments: undefined;
  updatePrBody: undefined;
  mergePr: undefined;
  setAutoFixEnabled: undefined;
  releaseWorktree: undefined;
  enableAutoMerge: undefined;
  disableAutoMerge: undefined;
  popBackgroundTaskSuggestion: undefined;
  getTeleportReadiness: undefined;
  teleportToCloud: undefined;
  respondToSSHPassword: undefined;
}
export interface LocalSessionsReturn {
  shareSession: {
  success: boolean;
  filePath?: string;
  error?: string;
};
  start: {
  sessionId: string;
};
  forkSession: {
  sessionId: string;
};
  sendMessage: void;
  setModel: void;
  setEffort: void;
  getEffort: void;
  setFastMode: void;
  getContextUsage: void;
  startSideChat: void;
  sendSideChatMessage: void;
  stopSideChat: void;
  summarizeSession: void;
  summarizeTranscript: void;
  stopSessionSummary: void;
  stop: void;
  interrupt: void;
  stopTask: void;
  cancelQueuedMessage: void;
  logCliEvent: void;
  clearSession: void;
  rewind: void;
  getUncommittedChanges: void;
  archive: void;
  unarchive: void;
  delete: void;
  updateSession: void;
  getSession: void;
  getSessionsForScheduledTask: void;
  getGitInfo: void;
  getLocalBranches: void;
  getGitDiff: void;
  getGitDiffStats: void;
  getDiffFileContent: void;
  getGitCommits: void;
  getCommitDiff: void;
  getTranscript: void;
  searchSessions: void;
  openInVSCode: void;
  getInstalledEditors: void;
  openInEditor: void;
  pickSessionFile: void;
  pickFileAtCwd: void;
  readFileAtCwd: void;
  readSessionFile: void;
  listSessionDirectory: void;
  readSessionImageAsDataUrl: void;
  writeSessionFile: void;
  startPty: void;
  stopPty: void;
  resizePty: void;
  writePty: void;
  startShellPty: {
  ok: boolean;
  error?: string;
  buffered?: string;
};
  stopShellPty: void;
  resizeShellPty: void;
  writeShellPty: void;
  getShellPtyBuffer: void;
  runBashCommand: {
  stdout: string;
  stderr: string;
  code?: number;
  error?: string;
};
  respondToToolPermission: void;
  checkTrust: {
  // unparsed: <no body>
};
  saveTrust: void;
  setPermissionMode: void;
  getPermissionMode: void;
  launchUltrareview: {
  // unparsed: <no body>
};
  submitFeedback: {
  feedbackId?: string;
  ccshareUrl?: string;
  unavailableReason?: string;
  isZdrOrg?: boolean;
  failureReason?: string;
  statusCode?: number;
  error?: string;
};
  addDirectories: void;
  getDefaultPermissionMode: void;
  getSupportedCommands: void;
  getAgents: void;
  createAgent: {
  success: boolean;
  filePath?: string;
  error?: string;
};
  getPlanForSession: void;
  setMcpServers: {
  enabledMcpTools: /* jOt */ unknown;
};
  replaceRemoteMcpServers: {
  enabledMcpTools: /* jOt */ unknown;
};
  replaceEnabledMcpTools: {
  enabledMcpTools: /* jOt */ unknown;
};
  setFocusedSession: void;
  setAvailableCodeModels: void;
  testSSHConnection: {
  // unparsed: <no body>
};
  validateSSHPath: {
  // unparsed: <no body>
};
  listSSHDirectory: {
  error?: string;
  // unparsed: !(Array.isArray(e.entries)&&e.entries.every(A=>ROt(A)))
};
  getSSHGitInfo: void;
  getSSHSupportedCommands: void;
  checkRemoteTrust: {
  // unparsed: <no body>
};
  resolveSSHSettings: {
  model?: /* T$A */ unknown;
  fastMode?: /* v$A */ unknown;
  fastModePerSessionOptIn?: /* v$A */ unknown;
  defaultPermissionMode?: /* T$A */ unknown;
  sshHostAllowlist?: /* _Ut */ unknown;
};
  ensureSSHConnected: void;
  setSSHConfigs: void;
  setTrustedSSHHosts: void;
  importCliSession: void;
  setVisibility: void;
  checkGhAvailable: void;
  listGhIssues: void;
  getGhIssue: void;
  isWorkingTreeDirty: void;
  getWorkingTreeStatus: void;
  commitAllChanges: {
  success: boolean;
  error?: string;
};
  stashWorkingTree: {
  success: boolean;
  error?: string;
};
  commitWipForBranchSwitch: {
  success: boolean;
  error?: string;
};
  discardWorkingTree: {
  success: boolean;
  error?: string;
};
  generateLocalPrContent: void;
  reviewDiff: {
  // unparsed: !(Array.isArray(e.comments)&&e.comments.every(A=>UOt(A)))
};
  ensureBranchPushed: {
  success: boolean;
  branch?: string;
  error?: string;
  errorType?: string;
};
  createLocalPr: {
  success: boolean;
  number?: number;
  url?: string;
  error?: string;
};
  getPrChecks: {
  success: boolean;
  prState?: string;
  mergeable?: string;
  mergeStateStatus?: string;
  reviewDecision?: string;
  autoMergeEnabled?: boolean;
  error?: string;
  // unparsed: typeof e.checks<"u"&&!(Array.isArray(e.checks)&&e.checks.every(A=>YOt(A)))
};
  getPrStateForBranch: {
  success: boolean;
  number?: number;
  state?: string;
  url?: string;
  baseRefName?: string;
  headRefName?: string;
  error?: string;
};
  getPrDetails: {
  success: boolean;
  title?: string;
  body?: string;
  error?: string;
};
  getPrReviewComments: {
  success: boolean;
  error?: string;
  // unparsed: typeof e.comments<"u"&&!(Array.isArray(e.comments)&&e.comments.every(A=>JOt(A)))
};
  updatePrBody: {
  success: boolean;
  error?: string;
};
  mergePr: {
  success: boolean;
  error?: string;
};
  setAutoFixEnabled: void;
  releaseWorktree: void;
  enableAutoMerge: {
  success: boolean;
  error?: string;
};
  disableAutoMerge: {
  success: boolean;
  error?: string;
};
  popBackgroundTaskSuggestion: void;
  getTeleportReadiness: void;
  teleportToCloud: void;
  respondToSSHPassword: void;
}

// ----- claude.web::NestDev -----
export interface NestDevArgs {
  getState: undefined;
  focus: undefined;
}
export interface NestDevReturn {
  getState: void;
  focus: void;
}

// ----- claude.web::OrbitDeploys -----
export interface OrbitDeploysArgs {
  setDeploy: undefined;
  removeDeploy: undefined;
  setPinned: undefined;
}
export interface OrbitDeploysReturn {
  setDeploy: void;
  removeDeploy: void;
  setPinned: void;
}

// ----- claude.web::QuickEntry -----
export interface QuickEntryArgs {
  setRecentChats: undefined;
}
export interface QuickEntryReturn {
  setRecentChats: void;
}

// ----- claude.web::Resources -----
export interface ResourcesArgs {
  fetchMentionOptions: undefined;
  handleMentionSelect: undefined;
  setFocusedCwd: undefined;
  searchFileContents: undefined;
  setFindInPageClaimed: undefined;
}
export interface ResourcesReturn {
  fetchMentionOptions: void;
  handleMentionSelect: {
  chipText: string;
  additionalText?: string;
  cuAppHint?: /* mGA */ unknown;
  // unparsed: typeof e.attachments<"u"&&!(Array.isArray(e.attachments)&&e.attachments.every(A=>NFt(A)))
};
  setFocusedCwd: void;
  searchFileContents: void;
  setFindInPageClaimed: void;
}

// ----- claude.web::WindowControl -----
export interface WindowControlArgs {
  resize: undefined;
  setThemeMode: {
  // unparsed: <no body>
};
  setIncognitoMode: undefined;
}
export interface WindowControlReturn {
  resize: void;
  setThemeMode: void;
  setIncognitoMode: void;
}
